ministryofjustice/hmpps-alerts-ui

integration_tests/e2e/createNewAlertCode.cy.ts, integration_tests/e2e/createNewAlertType.cy.ts, integration_tests/mockApis/alertsApi.ts, integration_tests/pages/addAnAlertCodeConfirmationPage.ts, integration_tests/pages/alertCodeSuccessPage.ts, integration_tests/pages/alertTypeSuccessPage.ts, integration_tests/pages/selectAnAlertType.ts, server/routes/createAlertCodeRoutes.test.ts, server/routes/createAlertCodeRoutes.ts, server/routes/index.ts, server/views/pages/createAlertCode/confirmation.njk, server/views/pages/createAlertCode/index.njk, server/views/pages/createAlertCode/partials/createAlertCodeErrorBanner.njk, server/views/pages/createAlertCode/success.njk, server/views/pages/createAlertType/confirmation.njk
* Fix the validation on the alert type selection
* Fix the tests for selecting a type
* Add skeleton for success page
* Requires AL-66 to actually save to the database
=> AL-65 add confirmation page & success skeleton

integration_tests/e2e/updateAlertType.cy.ts, integration_tests/mockApis/alertsApi.ts, integration_tests/pages/enterDescriptionForUpdateAlertType.ts, integration_tests/pages/index.ts, server/@types/express/index.d.ts, server/routes/createAlertCodeRoutes.test.ts, server/routes/createAlertCodeRoutes.ts, server/routes/deactivateAlertCodeRoutes.test.ts, server/routes/deactivateAlertCodeRoutes.ts, server/routes/index.ts, server/routes/updateAlertTypeRoutes.test.ts, server/routes/updateAlertTypeRoutes.ts, server/views/pages/partials/referenceDataPanels.njk, server/views/pages/updateAlertType/index.njk, server/views/pages/updateAlertType/partials/updateAlertTypeErrorBanner.njk, server/views/pages/updateAlertType/submitDescription.njk
Update Alert Type description,
homepage tile:
start page:
=> AL-77 + AL-78 Update Alert Type Description Homepage tile + start page

integration_tests/e2e/updateAlertType.cy.ts, integration_tests/pages/enterDescriptionForUpdateAlertType.ts, integration_tests/pages/page.ts, integration_tests/pages/updateAlertTypeDescriptionConfirmationPage.ts, server/routes/index.ts, server/routes/updateAlertTypeRoutes.test.ts, server/routes/updateAlertTypeRoutes.ts, server/views/pages/updateAlertType/confirmation.njk, server/views/pages/updateAlertType/partials/updateAlertTypeErrorBanner.njk, server/views/pages/updateAlertType/submitDescription.njk
=> AL-80 Update Alert Type Description confirmation screen

integration_tests/e2e/deactivateAlertCode.cy.ts, integration_tests/e2e/updateAlertCode.cy.ts, integration_tests/mockApis/alertsApi.ts, integration_tests/pages/enterDescriptionForUpdateAlertCode.ts, integration_tests/pages/index.ts, integration_tests/pages/selectAlertCodePage.ts, integration_tests/pages/updateAlertCodeDescriptionConfirmationPage.ts, integration_tests/pages/updateAlertCodeDescriptionSuccessPage.ts, server/@types/alerts/alertsApiTypes.ts, server/@types/alerts/index.d.ts, server/data/alertsApiClient.ts, server/routes/index.ts, server/routes/updateAlertCodeRoutes.test.ts, server/routes/updateAlertCodeRoutes.ts, server/views/pages/partials/referenceDataPanels.njk, server/views/pages/updateAlertCode/alertCode.njk, server/views/pages/updateAlertCode/confirmation.njk, server/views/pages/updateAlertCode/index.njk, server/views/pages/updateAlertCode/partials/updateAlertCodeErrorBanner.njk, server/views/pages/updateAlertCode/submitDescription.njk, server/views/pages/updateAlertCode/success.njk
=> AL-82 Update Alert Code Description

package-lock.json, package.json, server/@schemas/AlertCodeRequests.ts, server/@schemas/AlertTypeRequests.ts, server/@types/alerts/index.d.ts, server/routes/createAlertCodeRoutes.test.ts, server/routes/createAlertCodeRoutes.ts, server/routes/createAlertTypeRoutes.test.ts, server/routes/createAlertTypeRoutes.ts, server/routes/updateAlertCodeRoutes.test.ts, server/routes/updateAlertCodeRoutes.ts, server/routes/updateAlertTypeRoutes.ts
https://github.com/ministryofjustice/hmpps-alerts-ui/assets/109068236/14461e00-95ab-4944-8239-ccce4879fda2
https://github.com/ministryofjustice/hmpps-alerts-ui/assets/109068236/38c20fa3-1a37-4594-97a2-077af178e7f7
=> feat: use zod for validation

integration_tests/mockApis/alertsApi.ts, server/data/alertsApiClient.ts
=> MIAD-225 Add query param ?allowInactiveCode=true to create alert api call

assets/js/extra/alerts.js, integration_tests/mockApis/alertsApi.ts, server/@types/express/index.d.ts, server/errorHandler.test.ts, server/middleware/insertJourneyIdentifier.ts, server/middleware/journeyStateMachine.ts, server/middleware/redirectCheckAnswersMiddleware.ts, server/middleware/setUpJourneyData.test.ts, server/middleware/setUpJourneyData.ts, server/routes/index.ts, server/routes/journeys/bulk-alerts/controller.ts, server/routes/journeys/bulk-alerts/routes.ts, server/routes/journeys/bulk-alerts/schemas.ts, server/routes/journeys/bulk-alerts/test.cy.ts, server/routes/journeys/bulk-alerts/view.njk, server/routes/journeys/routes.ts, server/utils/nunjucksSetup.ts
=> MIAD-198 /bulk-alerts (select alert) screen

.circleci/config.yml, integration_tests/utils/e2eTestUtils.ts, package-lock.json, package.json, server/@types/express/index.d.ts, server/routes/journeys/bulk-alerts/enter-alert-reason/controller.ts, server/routes/journeys/bulk-alerts/enter-alert-reason/view.njk, server/routes/journeys/bulk-alerts/how-to-add-prisoners/controller.ts, server/routes/journeys/bulk-alerts/how-to-add-prisoners/routes.ts, server/routes/journeys/bulk-alerts/how-to-add-prisoners/schemas.ts, server/routes/journeys/bulk-alerts/how-to-add-prisoners/tests.cy.ts, server/routes/journeys/bulk-alerts/how-to-add-prisoners/view.njk, server/routes/journeys/bulk-alerts/routes.ts, server/routes/journeys/routes.ts
=> MIAD-199 /bulk-alerts/how-to-add-prisoners screen

assets/js/index.js, assets/scss/application.scss, assets/scss/components/_search-input.scss, integration_tests/mockApis/prisonerSearchApi.ts, package-lock.json, package.json, server/@types/express/index.d.ts, server/data/prisonerSearchApiClient.ts, server/middleware/validationMiddleware.ts, server/routes/journeys/bulk-alerts/routes.ts, server/routes/journeys/bulk-alerts/select-prisoner/controller.ts, server/routes/journeys/bulk-alerts/select-prisoner/query/controller.ts, server/routes/journeys/bulk-alerts/select-prisoner/query/routes.ts, server/routes/journeys/bulk-alerts/select-prisoner/query/schemas.ts, server/routes/journeys/bulk-alerts/select-prisoner/routes.ts, server/routes/journeys/bulk-alerts/select-prisoner/schemas.ts, server/routes/journeys/bulk-alerts/select-prisoner/tests.cy.ts, server/routes/journeys/bulk-alerts/select-prisoner/view.njk, server/routes/tsconfig.json, server/utils/nunjucksSetup.ts, server/utils/utils.ts
=> MIAD-200 /bulk-alerts/select-prisoner screen

server/routes/journeys/bulk-alerts/how-to-add-prisoners/controller.ts, server/routes/journeys/bulk-alerts/how-to-add-prisoners/tests.cy.ts, server/routes/journeys/bulk-alerts/how-to-add-prisoners/view.njk, server/routes/journeys/bulk-alerts/review-prisoners/controller.ts, server/routes/journeys/bulk-alerts/review-prisoners/routes.ts, server/routes/journeys/bulk-alerts/review-prisoners/tests.cy.ts, server/routes/journeys/bulk-alerts/review-prisoners/view.njk, server/routes/journeys/bulk-alerts/routes.ts, server/routes/journeys/bulk-alerts/select-prisoner/controller.ts, server/routes/journeys/bulk-alerts/select-prisoner/tests.cy.ts, server/routes/journeys/bulk-alerts/select-prisoner/view.njk
=> MIAD-202 /bulk-alerts/review-prisoners screen

server/@types/express/index.d.ts, server/routes/journeys/bulk-alerts/routes.ts, server/routes/journeys/bulk-alerts/select-upload-logic/controller.ts, server/routes/journeys/bulk-alerts/select-upload-logic/routes.ts, server/routes/journeys/bulk-alerts/select-upload-logic/schemas.ts, server/routes/journeys/bulk-alerts/select-upload-logic/tests.cy.ts, server/routes/journeys/bulk-alerts/select-upload-logic/view.njk
=> MIAD-203 /bulk-alerts/select-upload-logic screen

integration_tests/mockApis/alertsApi.ts, server/@types/alerts/alertsApiTypes.ts, server/@types/alerts/index.d.ts, server/data/alertsApiClient.ts, server/middleware/removeTrailingSlashMiddleware.test.ts, server/middleware/removeTrailingSlashMiddleware.ts, server/routes/add-any-alert/controller.ts, server/routes/index.ts, server/routes/journeys/bulk-alerts/check-answers/controller.ts, server/routes/journeys/bulk-alerts/check-answers/routes.ts, server/routes/journeys/bulk-alerts/check-answers/tests.cy.ts, server/routes/journeys/bulk-alerts/check-answers/view.njk, server/routes/journeys/bulk-alerts/controller.ts, server/routes/journeys/bulk-alerts/enter-alert-reason/controller.ts, server/routes/journeys/bulk-alerts/how-to-add-prisoners/tests.cy.ts, server/routes/journeys/bulk-alerts/how-to-add-prisoners/view.njk, server/routes/journeys/bulk-alerts/review-prisoners/controller.ts, server/routes/journeys/bulk-alerts/routes.ts, server/routes/journeys/bulk-alerts/select-prisoner/controller.ts, server/routes/journeys/bulk-alerts/upload-prisoner-list/controller.ts
=> MIAD-204 /bulk-alerts/check-answers screen

integration_tests/mockApis/alertsApi.ts, server/@types/express/index.d.ts, server/routes/journeys/bulk-alerts/check-answers/controller.ts, server/routes/journeys/bulk-alerts/check-answers/routes.ts, server/routes/journeys/bulk-alerts/check-answers/tests.cy.ts, server/routes/journeys/bulk-alerts/confirmation/controller.ts, server/routes/journeys/bulk-alerts/confirmation/routes.ts, server/routes/journeys/bulk-alerts/confirmation/tests.cy.ts, server/routes/journeys/bulk-alerts/confirmation/view.njk, server/routes/journeys/bulk-alerts/routes.ts, server/routes/view.njk
=> MIAD-205 /bulk-alerts/confirmation screen

.circleci/config.yml, .gitignore, Dockerfile, helm_deploy/hmpps-alerts-ui/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, package-lock.json, package.json, server/app.ts, server/config.ts, server/middleware/sentryMiddleware.ts, server/middleware/setUpWebSecurity.ts, server/sentry.ts, server/views/partials/layout.njk
=> MIAD-206 Sentry integration

package-lock.json, server/routes/view.njk
Temporarily remove Bulk Alerts card from homepage
and npm audit fix
=> Temporarily remove Bulk Alerts card from homepage

server/@types/express/index.d.ts, server/middleware/validationMiddleware.ts, server/routes/journeys/bulk-alerts/check-answers/controller.ts, server/routes/journeys/bulk-alerts/check-answers/view.njk, server/routes/journeys/bulk-alerts/confirmation/tests.cy.ts, server/routes/journeys/bulk-alerts/confirmation/view.njk, server/routes/journeys/bulk-alerts/controller.ts, server/routes/journeys/bulk-alerts/e2e.cy.ts, server/routes/journeys/bulk-alerts/enter-alert-reason/controller.ts, server/routes/journeys/bulk-alerts/enter-alert-reason/schemas.ts, server/routes/journeys/bulk-alerts/enter-alert-reason/tests.cy.ts, server/routes/journeys/bulk-alerts/routes.ts, server/routes/journeys/bulk-alerts/upload-prisoner-list/schemas.ts, server/routes/view.njk
=> MIAD-259 Update /bulk-alerts journey wordings and routing logic

assets/js/form-spinner.js, assets/js/index.js, assets/scss/application.scss, assets/scss/components/_form-spinner.scss, server/config.ts, server/middleware/overrideTimeoutMiddleware.ts, server/middleware/setUpMultipartFormDataParsing.ts, server/routes/journeys/bulk-alerts/check-answers/routes.ts, server/routes/journeys/bulk-alerts/check-answers/view.njk, server/routes/journeys/bulk-alerts/select-upload-logic/view.njk, server/routes/journeys/bulk-alerts/upload-prisoner-list/routes.ts, server/routes/journeys/bulk-alerts/upload-prisoner-list/schemas.ts, server/routes/journeys/bulk-alerts/upload-prisoner-list/view.njk
=> MIAD-261 Handle large number of prisoners for /bulk-alerts journey

server/middleware/journeyStateMachine.ts, server/routes/index.ts, server/routes/journeys/bulk-alerts/confirmation/controller.ts, server/routes/journeys/bulk-alerts/select-prisoner/controller.ts, server/routes/journeys/bulk-alerts/upload-prisoner-list/schemas.ts, server/routes/journeys/routes.ts, server/utils/azureAppInsights.ts, server/utils/utils.ts
=> MIAD-261 appinsight middleware fix, and journey data size reduction

server/routes/journeys/bulk-alerts/cancellation-check/controller.ts, server/routes/journeys/bulk-alerts/cancellation-check/routes.ts, server/routes/journeys/bulk-alerts/cancellation-check/tests.cy.ts, server/routes/journeys/bulk-alerts/cancellation-check/view.njk, server/routes/journeys/bulk-alerts/check-answers/tests.cy.ts, server/routes/journeys/bulk-alerts/check-answers/view.njk, server/routes/journeys/bulk-alerts/routes.ts
=> MIAD-432 Add Cancellation Confirmation page to Upload Bulk Alerts journey

server/routes/journeys/bulk-alerts/check-answers/tests.cy.ts, server/routes/journeys/bulk-alerts/check-answers/view.njk, server/routes/journeys/bulk-alerts/enter-alert-reason/view.njk, server/routes/journeys/bulk-alerts/upload-prisoner-list/schemas.ts, server/routes/journeys/bulk-alerts/upload-prisoner-list/view.njk
=> MIAD-522 remediations to bulk alerts pages

server/@types/express/index.d.ts, server/routes/journeys/update-reference-data/routes.ts, server/routes/journeys/update-reference-data/select-change/controller.ts, server/routes/journeys/update-reference-data/select-change/routes.ts, server/routes/journeys/update-reference-data/select-change/schemas.ts, server/routes/journeys/update-reference-data/select-change/tests.cy.ts, server/routes/journeys/update-reference-data/select-change/view.njk, server/routes/journeys/update-reference-data/view.njk
=> MIAD-466 select change type page

server/@types/express/index.d.ts, server/app.ts, server/middleware/handleApiError.ts, server/middleware/setUpMultipartFormDataParsing.ts, server/routes/journeys/routes.ts, server/routes/journeys/update-reference-data/add-alert-type/controller.ts, server/routes/journeys/update-reference-data/add-alert-type/routes.ts, server/routes/journeys/update-reference-data/add-alert-type/schemas.ts, server/routes/journeys/update-reference-data/add-alert-type/tests.cy.ts, server/routes/journeys/update-reference-data/add-alert-type/view.njk, server/routes/journeys/update-reference-data/check-answers/controller.ts, server/routes/journeys/update-reference-data/check-answers/routes.ts, server/routes/journeys/update-reference-data/check-answers/tests.cy.ts, server/routes/journeys/update-reference-data/check-answers/view.njk, server/routes/journeys/update-reference-data/confirmation/controller.ts, server/routes/journeys/update-reference-data/confirmation/routes.ts, server/routes/journeys/update-reference-data/confirmation/tests.cy.ts, server/routes/journeys/update-reference-data/confirmation/view.njk, server/routes/journeys/update-reference-data/routes.ts
=> MIAD-472 Add create alert type pages

integration_tests/mockApis/alertsApi.ts, server/@types/express/index.d.ts, server/routes/journeys/update-reference-data/routes.ts, server/routes/journeys/update-reference-data/select-alert-type/controller.ts, server/routes/journeys/update-reference-data/select-alert-type/routes.ts, server/routes/journeys/update-reference-data/select-alert-type/schemas.ts, server/routes/journeys/update-reference-data/select-alert-type/tests.cy.ts, server/routes/journeys/update-reference-data/select-alert-type/view.njk
=> MIAD-467 select alert type page

.circleci/config.yml, server/routes/journeys/update-reference-data/add-alert-code/controller.ts, server/routes/journeys/update-reference-data/add-alert-code/routes.ts, server/routes/journeys/update-reference-data/add-alert-code/schemas.ts, server/routes/journeys/update-reference-data/add-alert-code/tests.cy.ts, server/routes/journeys/update-reference-data/add-alert-code/view.njk, server/routes/journeys/update-reference-data/add-alert-type/routes.ts, server/routes/journeys/update-reference-data/add-alert-type/schemas.ts, server/routes/journeys/update-reference-data/add-alert-type/tests.cy.ts, server/routes/journeys/update-reference-data/check-answers/controller.ts, server/routes/journeys/update-reference-data/check-answers/partial/add-new-alert-code.njk, server/routes/journeys/update-reference-data/check-answers/partial/add-new-alert-type.njk, server/routes/journeys/update-reference-data/check-answers/tests.cy.ts, server/routes/journeys/update-reference-data/check-answers/view.njk, server/routes/journeys/update-reference-data/confirmation/tests.cy.ts, server/routes/journeys/update-reference-data/confirmation/view.njk, server/routes/journeys/update-reference-data/routes.ts, server/routes/journeys/update-reference-data/select-alert-type/controller.ts, server/routes/journeys/update-reference-data/select-alert-type/tests.cy.ts, server/utils/utils.ts
MIAD-468
add new alert code journey pages:
and fix select-alert-type radio labels:
(previously i missed the sort order, text label template, and deactivated tag, ie: basically everything)
=> MIAD-468 new alert code journey pages

server/routes/journeys/update-reference-data/check-answers/controller.ts, server/routes/journeys/update-reference-data/check-answers/partial/edit-alert-code.njk, server/routes/journeys/update-reference-data/check-answers/tests.cy.ts, server/routes/journeys/update-reference-data/check-answers/view.njk, server/routes/journeys/update-reference-data/confirmation/tests.cy.ts, server/routes/journeys/update-reference-data/confirmation/view.njk, server/routes/journeys/update-reference-data/edit-alert-code/controller.ts, server/routes/journeys/update-reference-data/edit-alert-code/routes.ts, server/routes/journeys/update-reference-data/edit-alert-code/schemas.ts, server/routes/journeys/update-reference-data/edit-alert-code/tests.cy.ts, server/routes/journeys/update-reference-data/edit-alert-code/view.njk, server/routes/journeys/update-reference-data/routes.ts
=> MIAD-469 edit alert code journey pages

server/routes/journeys/update-reference-data/check-answers/controller.ts, server/routes/journeys/update-reference-data/check-answers/partial/edit-alert-type.njk, server/routes/journeys/update-reference-data/check-answers/tests.cy.ts, server/routes/journeys/update-reference-data/check-answers/view.njk, server/routes/journeys/update-reference-data/confirmation/tests.cy.ts, server/routes/journeys/update-reference-data/confirmation/view.njk, server/routes/journeys/update-reference-data/edit-alert-type/controller.ts, server/routes/journeys/update-reference-data/edit-alert-type/routes.ts, server/routes/journeys/update-reference-data/edit-alert-type/schemas.ts, server/routes/journeys/update-reference-data/edit-alert-type/tests.cy.ts, server/routes/journeys/update-reference-data/edit-alert-type/view.njk, server/routes/journeys/update-reference-data/routes.ts
=> MIAD-473 edit alert type journey pages
